name: HTTPS certificate

on:
  schedule:
    - cron: "17 4 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: onnimonni/trusted-https-certificate-to-artifacts-action@419a9cce22acadc0065c2c309a7a1afd555a0e85 # v1.2.0
        with:
          domains: ${{ vars.HTTPS_CERTIFICATE_DOMAINS }}
          cloudflare-token: ${{ secrets.HTTPS_CERTIFICATE_CLOUDFLARE_TOKEN }}
