name: HTTPS certificate

on:
  schedule:
    - cron: "17 4 1,16 * *"
  workflow_dispatch:

permissions: {}

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: onnimonni/trusted-https-certificate-to-artifacts-action@6836fa628b8cf66a3039d5f5007d50fb25d6a2c2 # v2.1.0
        with:
          domains: ${{ vars.HTTPS_CERTIFICATE_DOMAINS }}
          cloudflare-token: ${{ secrets.HTTPS_CERTIFICATE_CLOUDFLARE_TOKEN }}
