name: HTTPS certificate

on:
  schedule:
    - cron: "17 4 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: onnimonni/trusted-https-certificate-to-artifacts-action@1951d1d40a6e169df2357941a71beed9fb0c67d8 # v1.1.0
        with:
          domains: ${{ vars.HTTPS_CERTIFICATE_DOMAINS }}
          cloudflare-token: ${{ secrets.HTTPS_CERTIFICATE_CLOUDFLARE_TOKEN }}
